Braile.alphabet.en = {
    "a"   : "o- -- --",
    "b"   : "o- o- --",
    "c"   : "oo -- --",
    "d"   : "oo -o --",
    "e"   : "o- -o --",
    "f"   : "oo o- --",
    "g"   : "oo oo --",
    "h"   : "o- oo --",
    "i"   : "-o o- --",
    "j"   : "-o oo --",
    "k"   : "o- -- o-",
    "l"   : "o- o- o-",
    "m"   : "oo -- o-",
    "n"   : "oo -o o-",
    "o"   : "o- -o o-",
    "p"   : "oo o- o-",
    "q"   : "oo oo o-",
    "r"   : "o- oo o-",
    "s"   : "-o o- o-",
    "t"   : "-o oo o-",
    "u"   : "o- -- oo",
    "v"   : "o- o- oo",
    "w"   : "-- -o oo",
    "x"   : "oo -- oo",
    "y"   : "oo -o oo",
    "z"   : "o- -o oo",
    "and" : "oo o- oo",
    "for" : "oo oo oo",
    "of"  : "o- oo oo",
    "with": "-o oo oo",
    "ch"  : "o- -- -o",
    "gh"  : "o- o- -o",
    "sh"  : "oo -- -o",
    "th"  : "oo -o -o",
    "the" : "-o o- oo",
    "wh"  : "o- -o -o",
    "ed"  : "oo o- -o",
    "er"  : "oo oo -o",
    "ou"  : "o- oo -o",
    "ow"  : "-o o- -o",
    "ea"  : "-- o- --",
    "bb"  : "-- o- o-",
    "cc"  : "-- oo --",
    "dd"  : "-- oo -o",
    "en"  : "-- o- -o",
    "ff"  : "-- oo o-",
    "gg"  : "-- oo oo",
    "in"  : "-- -o o-",
    "  "  : "-- -- --"
}

if(typeof module != "undefined")
    module.export = Braile.alphabet.en;